### ISSUE TITLE
Controllo IP errato.

### ISSUE THREAD

**Issue by LucaTheHacker** [GiacomoDevIT/GjacBot#10]
Dalla linea 3 alla 14 hai creato un codice lungo e contorto, semplificabile in una o due righe di codice, avendo anche velocità maggiori.

Per maggiore sicurezza ti consiglio anche di mettere un controllo tramite GET per verificare se il token corrisponde, in tal modo sarai sicuro che chi utilizzerà il bot sia necessariamente autorizzato e che non vengano fatte richieste dal bot errato.

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker Grazie per i consigli. Li metto in pratica.
