### ISSUE TITLE
Miglioramenti

### ISSUE THREAD

**Issue by LucaTheHacker** [GiacomoDevIT/GjacBot#11]
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L41
la parte di confronto è inutile, if($database) funzionerà ugualmente

**Comment by GiacomoDevIT** [comment]
Lo metto perchè la gente può non usarlo per comodità

**Comment by LucaTheHacker** [comment]
```
$database = false;
if($database){echo "test";}
result: ""
```
```
$database = true;
if($database){echo "test";}
result: "test"

```

**Comment by GiacomoDevIT** [comment]
Io ho messo if true

**Comment by LucaTheHacker** [comment]
eh, ma è inutile mettere === true, visto che l'if lo andrà a controllare automaticamente

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker Okay, quindi tolgo la if

**Comment by LucaTheHacker** [comment]
no, devi lasciare if($database) e funziona ugualmente

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker Okay

**Comment by LucaTheHacker** [comment]
if per natura controlla se il paramentro indicato è true o false, e nel caso true esegue la parte di codice indicata

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker Grazie

**Comment by LucaTheHacker** [comment]
di nulla
