### ISSUE TITLE
isset mancanti

### ISSUE THREAD

**Issue by LucaTheHacker** [GiacomoDevIT/GjacBot#13]
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L7
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L8
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L9
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L10
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L11
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L12
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L13
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L14
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L15
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L16
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L17
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L18
https://github.com/GiacomoDevIT/GjacBot/blob/42373784daad3e5bd259465ebc7e3bc70153e6b0/bot.php#L19

In tutte queste righe vi è un errore abbastanza grave, mancano tutti gli isset, quindi se le var non sono settate il codice restituirà 400 errori

**Comment by GiacomoDevIT** [comment]
var_dump(isset($update['message']['text']->$testo));   

così okay-?

**Comment by Pato05** [comment]
Lol

**Comment by LucaTheHacker** [comment]
@GiacomoDevIT non intendo usare un isset nel vardump intendo usare

if(isset($update['message']['text'])){$text = $update['message']['text'];}
in questo modo se il campo text non esiste non ti restituisce errori

**Comment by LucaTheHacker** [comment]
e oltre a quello potrai usare isset($text) in un if per controllare se la variabile esiste, in questo modo sei anche più veloce, visto che isset è una decina di volte più veloce di $var !== "" da quel che ricordo

**Comment by GiacomoDevIT** [comment]
sono tante righe, creo un file a parte?

**Comment by LucaTheHacker** [comment]
non necessariamente, essendo dei semplici isset non necessiti di grande intentazione, puoi fare tutto in riga

**Comment by LucaTheHacker** [comment]
altrimenti fai un file per le funzioni, uno per le var e uno con i require

**Comment by GiacomoDevIT** [comment]
https://imgur.com/a/d3ah7L5 ah

**Comment by LucaTheHacker** [comment]
non hai capito

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker eh no

**Comment by LucaTheHacker** [comment]
ogni isset è a se stante, se io ho un first_name posso anche avere un last_name

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker cioè

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker così va bene anche se è lungo?

**Comment by LucaTheHacker** [comment]
if(isset()){}
if(isset()){}
if(isset()){}

il formato è questo

**Comment by LucaTheHacker** [comment]
> @LucaTheHacker così va bene anche se è lungo?

no, non funzionerà mai

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker e come dovrei farlo

**Comment by LucaTheHacker** [comment]
if (isset(/*Controllo esistenza var1*/)) {/*Assegnazione var1*/}
if (isset(/*Controllo esistenza var2*/)) {/*Assegnazione var2*/}
if (isset(/*Controllo esistenza var3*/)) {/*Assegnazione var3*/}
