### ISSUE TITLE
200 chars?

### ISSUE THREAD

**Issue by LucaTheHacker** [GiacomoDevIT/GjacBot#16]
https://github.com/GiacomoDevIT/GjacBot/blob/164457ec1f9159a2fa7f69350ef366d1916567ca/db.php#L10

Hai lasciato username a 200 chars quando il limite di telegram è 32

**Comment by LucaTheHacker** [comment]
inoltre ti consiglio di fare creare la tabella manualmente la prima volta e non di eseguire la query ad ogni giro

**Comment by GiacomoDevIT** [comment]
inoltre ti consiglio di fare creare la tabella manualmente la prima volta e non di eseguire la query ad ogni giro

sto facendo, lo rilascio in 3.0.2
