### ISSUE TITLE
Errore in PHP7.*

### ISSUE THREAD

**Issue by LucaTheHacker** [GiacomoDevIT/GjacBot#17]
https://github.com/GiacomoDevIT/GjacBot/blob/8a618d2399b6c40bf9ae79ab376ac2f678cc9e00/funzioni.php#L14
In questa riga dovresti usare `$menu = ''` in questo modo se l'utente non va ad inserire nulla non riceverà un errore.

https://github.com/GiacomoDevIT/GjacBot/blob/8a618d2399b6c40bf9ae79ab376ac2f678cc9e00/funzioni.php#L17
in questa dovresti prima controllare se $menu è diverso da "", altrimenti rischi di inviare tastiere nulle.

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker fatt

**Comment by LucaTheHacker** [comment]
> @LucaTheHacker fatt

Apposto

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker no spe non va

**Comment by GiacomoDevIT** [comment]
nn va

**Comment by GiacomoDevIT** [comment]
lo ho fatto in più modi
