### ISSUE TITLE
Indentazione fatta male

### ISSUE THREAD

**Issue by LucaTheHacker** [GiacomoDevIT/GjacBot#2]
é impossibile usare il codice vista l'indentazione pessima, spesso gli updates non arrivano al bot.

**Comment by GiacomoDevIT** [comment]
Devo ricordarti che php non utilizza alcun metodo di indentazione? Super dev sei eh

**Comment by LucaTheHacker** [comment]
Signor zuccamberg, mi pare più che ovvio che l'indentazione di un codice debba essere fatta correttamente, altrimenti diventa scomodo usarlo!

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker Eh allora non dire che è impossibile usarlo dametto

**Comment by LucaTheHacker** [comment]
Signor ScamDev, la invito a rivolgersi usando il mio username e non dati personali a sproposito (soprattutto dopo aver truffato varie persone), grazie!

Inoltre se secondo te l'indent è inutile datti all'hippica, o magari all'hi(m)piccagione

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker 😂🤣

**Comment by LucaTheHacker** [comment]
Adesso passi a postare i siti altrui, AHHAHAHAHAH.

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker 🤣🤣😂
