### ISSUE TITLE
sta roba non va

### ISSUE THREAD

**Issue by LucaTheHacker** [GiacomoDevIT/GjacBot#21]
https://github.com/GiacomoDevIT/GjacBot/blob/4613b8d26eeb6df8f4a0008ae5a2902efbf4ceaf/funzioni.php#L30

hai aperto 2 volte il tag di php senza mai chiuderlo

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker Si è sminchiato

**Comment by LucaTheHacker** [comment]
MI correggo, hai duplicato il tutto due volte

**Comment by Pato05** [comment]
this is murda 💩
