### ISSUE TITLE
Error at line 4

### ISSUE THREAD

**Issue by LucaTheHacker** [GiacomoDevIT/GjacBot#3]
From me and Turi,

**Comment by LucaTheHacker** [comment]
echo "<i align="center">GjacBot</i>";

**Comment by LucaTheHacker** [comment]
is wrong, u should use 
`echo "<i align="center">GjacBot</i>";`
`echo '<i align="center">GjacBot</i>';`
or 
`echo "<i align=\"center\">GjacBot</i>";`

**Comment by GiacomoDevIT** [comment]
@LucaTheHacker Non è sbagliato 🤣🤣

**Comment by LucaTheHacker** [comment]
Sarò scarso in php ma quello è un errore.

**Comment by davtur19** [comment]
@GiacomoDevIT allora provalo il codice...

**Comment by LucaTheHacker** [comment]
Fixato, chiudo.
