### ISSUE TITLE
Errori ovunque

### ISSUE THREAD

**Issue by davtur19** [GiacomoDevIT/GjacBot#4]
sistema l'indentazione (tutto)
[inverti questo if e non lasciarlo vuoto](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L3)
[inutili, leva](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L37)
[inutile, leva](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L35)
[usa true invece di 1](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L33)
[vedi sopra](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L36)
[metti un return alla povera funzione](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L44)
[vedi sopra](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L51)
[le virgolette a website...](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L49)
[hai dimenticato una &](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L58)
[usa http_build_query](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L49)
[inutile, leva](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L60)
[inutile, leva](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L63)
[variabile che non esiste](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/db.php#L29)
[ancora che non sei in grado di fare una query decente](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/db.php#L30)
[usa pdo](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/db.php#L6) o [mysql](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/db.php#L25) deciditi
[se usi mysql](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/db.php#L25), almeno usa mysqli_* che mysql_* è deprecato in PHP7
[non può funzionare](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L2), [leggi le docs](https://core.telegram.org/bots/webhooks#the-short-version)
[generà errori nel caso l'update non contenga il chat id](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L11)
[vedi sopra](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L12)
[variabile duplicata per nulla](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/db.php#L27)
[tutto sto pezzo non funziona, sia per la sintassi, sia come logica](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/db.php#L30)
[non dovresti creare una tabella a ogni esecuzione del codice...](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/db.php#L9)
[Codice copiato](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/start.php#L32) da qua https://codular.com/curl-with-php
perché sul db c'è un [campo page varchar(200)](https://github.com/GiacomoDevIT/GjacBot/blob/c02f91ed165fba9723f0cebb69fdad1938c65e86/db.php#L12)?
perché fare un campo username varchar(200) quando gli username comunque non possono superare i 32 caratteri?
perché crei un [campo id bigint](https://github.com/GiacomoDevIT/GjacBot/blob/c02f91ed165fba9723f0cebb69fdad1938c65e86/db.php#L11) quando può usare chat_id come chiave primaria?
rinfacci agli altri l'uso di `==` al posto di `===` quando in [tu stesso usi](https://github.com/GiacomoDevIT/GjacBot/blob/c02f91ed165fba9723f0cebb69fdad1938c65e86/db.php#L17) `!=` al posto di `!==`

meno male che hai scritto ["Testata su PHP5.6 e PHP7"](https://github.com/GiacomoDevIT/GjacBot/blob/351bacfc30323e11668d6e88d465e4238ce83ffb/README.md#gjacbot), figuriamoci se non fosse testato, siccome allo stato attuale crasha su ogni versione e su PHP7 non funzionerà mai con mysql_*

Sei uno script kiddie che continua a copiare codice... impara a programmare...

**Comment by davtur19** [comment]
[variabile duplicata per nulla](https://github.com/GiacomoDevIT/GjacBot/blob/master/db.php#L27)
[tutto sto pezzo non funziona, sia per la sintassi, sia come logica](https://github.com/GiacomoDevIT/GjacBot/blob/master/db.php#L30)
[non dovresti creare una tabella a ogni esecuzione del codice...](https://github.com/GiacomoDevIT/GjacBot/blob/master/db.php#L9)

**Comment by LucaTheHacker** [comment]
+1
